"""Added is_pro to users table

Revision ID: ca3ea5643aad
Revises: bdfd7ea547c5
Create Date: 2025-05-04 15:50:00.265330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3ea5643aad'
down_revision: Union[str, None] = 'bdfd7ea547c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('is_pro', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'is_pro')
    # ### end Alembic commands ###
